import {
  LayoutDashboard,
  UsersRound,
  Globe,
  ShieldBan,
  Ticket,
  ActivitySquare,
  Utensils,
  Stethoscope,
  BadgeCheck,
  BookOpen,
  ShoppingCart,
  Bell,
  Wallet,
  CreditCard,
  Tags,
  ScrollText,
  AlertTriangle,
  Database,
  Clapperboard,
  HandCoins,
  Store,
} from "lucide-react";
import type { NavItem, NavGroup } from "@holora/ui";

export const NAV: NavItem[] = [
  { id: "dashboard", label: "Dashboard", icon: LayoutDashboard, group: "core" },
  { id: "users", label: "User Management", icon: UsersRound, group: "core" },
  { id: "communities", label: "Communities", icon: Globe, group: "ecosystem" },
  { id: "moderation", label: "Chat & Moderation", icon: ShieldBan, group: "ecosystem" },
  { id: "events", label: "Events", icon: Ticket, group: "ecosystem" },
  { id: "fitness", label: "Fitness Records", icon: ActivitySquare, group: "ecosystem" },
  { id: "nutrition", label: "Nutrition & Meals", icon: Utensils, group: "ecosystem" },
  { id: "recovery", label: "Recovery & Wellness", icon: Stethoscope, group: "ecosystem" },
  { id: "trainers", label: "Trainers & Booking", icon: BadgeCheck, group: "ecosystem" },
  { id: "studio", label: "Studio & Videos", icon: Clapperboard, group: "ecosystem" },
  { id: "content", label: "Content Plans", icon: BookOpen, group: "ecosystem" },
  { id: "shop", label: "Shop & Orders", icon: ShoppingCart, group: "ecosystem" },
  { id: "shop-config", label: "Store Config", icon: Store, group: "ecosystem" },
  { id: "notifications", label: "Notifications", icon: Bell, group: "ecosystem" },
  { id: "finance", label: "Finance & Wallets", icon: Wallet, group: "ecosystem" },
  { id: "trainer-earnings", label: "Trainer Earnings", icon: HandCoins, group: "business" },
  { id: "subscriptions", label: "Subscriptions", icon: CreditCard, group: "business" },
  { id: "pricing", label: "Pricing Engine", icon: Tags, group: "business" },
  { id: "audit", label: "Audit & Logs", icon: ScrollText, group: "operations" },
  { id: "alerts", label: "Alerts & Appeals", icon: AlertTriangle, group: "operations" },
  { id: "datasets", label: "Datasets", icon: Database, group: "operations" },
];

export const GROUPS: NavGroup[] = [
  { key: "core", label: "Core" },
  { key: "ecosystem", label: "Ecosystem" },
  { key: "business", label: "Business" },
  { key: "operations", label: "Operations" },
];
